"""split trilingual cv urls fixed

Revision ID: 678097a2072c
Revises: 408d807d4f0c
Create Date: 2026-02-24 16:18:10.082979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678097a2072c'
down_revision: Union[str, Sequence[str], None] = '408d807d4f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('cv_portuguese', sa.String(), nullable=True))
    op.alter_column('profile', 'cv_english',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profile', 'cv_spanish',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'cv_spanish',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profile', 'cv_english',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('profile', 'cv_portuguese')
    # ### end Alembic commands ###
