"""split trilingual cv urls

Revision ID: bc280a520d00
Revises: f0a7b5eeb8e7
Create Date: 2026-02-24 15:48:17.066449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc280a520d00'
down_revision: Union[str, Sequence[str], None] = 'f0a7b5eeb8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('cv_english', sa.String(), nullable=False))
    op.add_column('profile', sa.Column('cv_spanish', sa.String(), nullable=False))
    op.drop_column('profile', 'cv_filenames')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('cv_filenames', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('profile', 'cv_spanish')
    op.drop_column('profile', 'cv_english')
    # ### end Alembic commands ###
